Feature/details
Agilefreaks/BigriverBookstore-apple pull request #3
Opened 2019-03-08 08:38 UTC by c-Viorel

## Description
Main screen details 

## Related
https://trello.com/c/djnWRUNt/24-details-screen

## Documentation
1. Run the app
2. From book collection choose one

2019-03-08 08:38 UTC, c-Viorel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Details screen](https://trello.com/c/djnWRUNt/24-details-screen)

2019-03-08 11:45 UTC, MihaiPantiru requested changes

2019-03-08 11:45 UTC, MihaiPantiru commented on BigriverBookstore-apple/Sources/New Group/DetailsPhotoItem/CollectionViewDetailsPhotoItem.swift
> +            if let photoI = photoInfo {
@c-Viorel Maybe with guard and better variable name for 'photoI' this method will look better.

2019-03-08 11:45 UTC, MihaiPantiru commented on BigriverBookstore-apple/Sources/Controller/MainNavigationViewController.swift
> +        self.previousButton.animator().isHidden = children.count == 2
@c-Viorel I'm lost here :) Let's discuss offline on what you wanted to achieve here, maybe we have a better way to do it.

2019-03-08 11:45 UTC, MihaiPantiru commented on BigriverBookstore-appleTests/Utils/DateExtensionsTests.swift
> +    func testPerformanceExample() {
@c-Viorel testPerformanceExample is dead code. Let's remove it.

2019-03-08 11:45 UTC, MihaiPantiru commented on BigriverBookstore-apple/Sources/Utils/DateExtensions.swift
> +    func stringWith(format: Format = .yyyymmdd) -> String {
@c-Viorel Since DateFormatter() creation is pretty expensive, I propose to use a static one. I'll provide you some examples.

2019-03-08 13:09 UTC, MihaiPantiru approved these changes

2019-03-11 07:20 UTC, levelboy commented
Job done. Closing

2019-03-11 07:20 UTC, closed without merging